# Generated by Django 2.2.17 on 2020-11-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=4096, null=True)),
                ('ingest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=4096, null=True)),
                ('ingest', models.BooleanField(default=False)),
                ('form_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_commcare.FormControl')),
            ],
        ),
    ]
